import type { ShopCardShop } from "@/features/shop-card/shop-card";

export type CategoryShops = {
  title: string;
  slug: string;
  shops: ShopCardShop[];
};

export function useCategoryShops(): CategoryShops[] {
  // TODO: replace with API calls. Home page should fetch exactly 8 shops per category.
  return [
    {
      title: "Women",
      slug: "women",
      shops: [
        {
          id: "w1",
          name: "Chic Boutique",
          slug: "chic-boutique",
          images: [
            "https://picsum.photos/400/500?fashion1a",
            "https://picsum.photos/400/500?fashion1b",
            "https://picsum.photos/400/500?fashion1c",
          ],
          pfp: "https://picsum.photos/100/100?fashion1pfp",
          rating: 4.8,
          reviewCount: 234,
        },
        {
          id: "w2",
          name: "Urban Style",
          slug: "urban-style",
          images: [
            "https://picsum.photos/400/500?fashion2a",
            "https://picsum.photos/400/500?fashion2b",
            "https://picsum.photos/400/500?fashion2c",
          ],
          pfp: "https://picsum.photos/100/100?fashion2pfp",
          rating: 4.6,
          reviewCount: 189,
        },
        {
          id: "w3",
          name: "Elegant Wear",
          slug: "elegant-wear",
          images: [
            "https://picsum.photos/400/500?fashion3a",
            "https://picsum.photos/400/500?fashion3b",
            "https://picsum.photos/400/500?fashion3c",
          ],
          pfp: "https://picsum.photos/100/100?fashion3pfp",
          rating: 4.9,
          reviewCount: 421,
        },
        {
          id: "w4",
          name: "Casual Corner",
          slug: "casual-corner",
          images: [
            "https://picsum.photos/400/500?fashion4a",
            "https://picsum.photos/400/500?fashion4b",
            "https://picsum.photos/400/500?fashion4c",
          ],
          pfp: "https://picsum.photos/100/100?fashion4pfp",
          rating: 4.5,
          reviewCount: 156,
        },
        {
          id: "w5",
          name: "Trendy Threads",
          slug: "trendy-threads",
          images: [
            "https://picsum.photos/400/500?fashion5a",
            "https://picsum.photos/400/500?fashion5b",
            "https://picsum.photos/400/500?fashion5c",
          ],
          pfp: "https://picsum.photos/100/100?fashion5pfp",
          rating: 4.7,
          reviewCount: 298,
        },
        {
          id: "w6",
          name: "Classic Fits",
          slug: "classic-fits",
          images: [
            "https://picsum.photos/400/500?fashion6a",
            "https://picsum.photos/400/500?fashion6b",
            "https://picsum.photos/400/500?fashion6c",
          ],
          pfp: "https://picsum.photos/100/100?fashion6pfp",
          rating: 4.8,
          reviewCount: 312,
        },
        {
          id: "w7",
          name: "Modern Look",
          slug: "modern-look",
          images: [
            "https://picsum.photos/400/500?fashion7a",
            "https://picsum.photos/400/500?fashion7b",
            "https://picsum.photos/400/500?fashion7c",
          ],
          pfp: "https://picsum.photos/100/100?fashion7pfp",
          rating: 4.6,
          reviewCount: 245,
        },
        {
          id: "w8",
          name: "Vintage Vibes",
          slug: "vintage-vibes",
          images: [
            "https://picsum.photos/400/500?fashion8a",
            "https://picsum.photos/400/500?fashion8b",
            "https://picsum.photos/400/500?fashion8c",
          ],
          pfp: "https://picsum.photos/100/100?fashion8pfp",
          rating: 4.9,
          reviewCount: 567,
        },
      ],
    },
    {
      title: "Men",
      slug: "men",
      shops: [
        {
          id: "m1",
          name: "Street Style",
          slug: "street-style",
          images: [
            "https://picsum.photos/400/500?fashion9a",
            "https://picsum.photos/400/500?fashion9b",
            "https://picsum.photos/400/500?fashion9c",
          ],
          pfp: "https://picsum.photos/100/100?fashion9pfp",
          rating: 4.5,
          reviewCount: 178,
        },
        {
          id: "m2",
          name: "Formal Wear",
          slug: "formal-wear",
          images: [
            "https://picsum.photos/400/500?fashion10a",
            "https://picsum.photos/400/500?fashion10b",
            "https://picsum.photos/400/500?fashion10c",
          ],
          pfp: "https://picsum.photos/100/100?fashion10pfp",
          rating: 4.7,
          reviewCount: 289,
        },
        {
          id: "m3",
          name: "Boho Chic",
          slug: "boho-chic",
          images: [
            "https://picsum.photos/400/500?fashion11a",
            "https://picsum.photos/400/500?fashion11b",
            "https://picsum.photos/400/500?fashion11c",
          ],
          pfp: "https://picsum.photos/100/100?fashion11pfp",
          rating: 4.8,
          reviewCount: 334,
        },
        {
          id: "m4",
          name: "Minimalist",
          slug: "minimalist",
          images: [
            "https://picsum.photos/400/500?fashion12a",
            "https://picsum.photos/400/500?fashion12b",
            "https://picsum.photos/400/500?fashion12c",
          ],
          pfp: "https://picsum.photos/100/100?fashion12pfp",
          rating: 4.6,
          reviewCount: 201,
        },
        {
          id: "m5",
          name: "Designer Denim",
          slug: "designer-denim",
          images: [
            "https://picsum.photos/400/500?fashion14a",
            "https://picsum.photos/400/500?fashion14b",
            "https://picsum.photos/400/500?fashion14c",
          ],
          pfp: "https://picsum.photos/100/100?fashion14pfp",
          rating: 4.7,
          reviewCount: 276,
        },
        {
          id: "m6",
          name: "Athleisure",
          slug: "athleisure",
          images: [
            "https://picsum.photos/400/500?fashion15a",
            "https://picsum.photos/400/500?fashion15b",
            "https://picsum.photos/400/500?fashion15c",
          ],
          pfp: "https://picsum.photos/100/100?fashion15pfp",
          rating: 4.8,
          reviewCount: 389,
        },
        {
          id: "m7",
          name: "Maxi Dresses",
          slug: "maxi-dresses",
          images: [
            "https://picsum.photos/400/500?fashion13a",
            "https://picsum.photos/400/500?fashion13b",
            "https://picsum.photos/400/500?fashion13c",
          ],
          pfp: "https://picsum.photos/100/100?fashion13pfp",
          rating: 4.9,
          reviewCount: 412,
        },
        {
          id: "m8",
          name: "Modern Menswear",
          slug: "modern-menswear",
          images: [
            "https://picsum.photos/400/500?fashion7a",
            "https://picsum.photos/400/500?fashion7b",
            "https://picsum.photos/400/500?fashion7c",
          ],
          pfp: "https://picsum.photos/100/100?fashion7pfp",
          rating: 4.6,
          reviewCount: 245,
        },
      ],
    },
    {
      title: "Beauty",
      slug: "beauty",
      shops: [
        {
          id: "b1",
          name: "Glow Up Cosmetics",
          slug: "glow-up-cosmetics",
          images: [
            "https://picsum.photos/400/500?beauty1a",
            "https://picsum.photos/400/500?beauty1b",
            "https://picsum.photos/400/500?beauty1c",
          ],
          pfp: "https://picsum.photos/100/100?beauty1pfp",
          rating: 4.9,
          reviewCount: 512,
        },
        {
          id: "b2",
          name: "Natural Beauty",
          slug: "natural-beauty",
          images: [
            "https://picsum.photos/400/500?beauty2a",
            "https://picsum.photos/400/500?beauty2b",
            "https://picsum.photos/400/500?beauty2c",
          ],
          pfp: "https://picsum.photos/100/100?beauty2pfp",
          rating: 4.7,
          reviewCount: 298,
        },
        {
          id: "b3",
          name: "Skincare Haven",
          slug: "skincare-haven",
          images: [
            "https://picsum.photos/400/500?beauty4a",
            "https://picsum.photos/400/500?beauty4b",
            "https://picsum.photos/400/500?beauty4c",
          ],
          pfp: "https://picsum.photos/100/100?beauty4pfp",
          rating: 4.9,
          reviewCount: 634,
        },
        {
          id: "b4",
          name: "Beauty Box",
          slug: "beauty-box",
          images: [
            "https://picsum.photos/400/500?beauty5a",
            "https://picsum.photos/400/500?beauty5b",
            "https://picsum.photos/400/500?beauty5c",
          ],
          pfp: "https://picsum.photos/100/100?beauty5pfp",
          rating: 4.6,
          reviewCount: 187,
        },
        {
          id: "b5",
          name: "Pro Makeup",
          slug: "pro-makeup",
          images: [
            "https://picsum.photos/400/500?beauty8a",
            "https://picsum.photos/400/500?beauty8b",
            "https://picsum.photos/400/500?beauty8c",
          ],
          pfp: "https://picsum.photos/100/100?beauty8pfp",
          rating: 4.9,
          reviewCount: 445,
        },
        {
          id: "b6",
          name: "Organic Glow",
          slug: "organic-glow",
          images: [
            "https://picsum.photos/400/500?beauty9a",
            "https://picsum.photos/400/500?beauty9b",
            "https://picsum.photos/400/500?beauty9c",
          ],
          pfp: "https://picsum.photos/100/100?beauty9pfp",
          rating: 4.8,
          reviewCount: 312,
        },
        {
          id: "b7",
          name: "Cosmetic Corner",
          slug: "cosmetic-corner",
          images: [
            "https://picsum.photos/400/500?beauty11a",
            "https://picsum.photos/400/500?beauty11b",
            "https://picsum.photos/400/500?beauty11c",
          ],
          pfp: "https://picsum.photos/100/100?beauty11pfp",
          rating: 4.7,
          reviewCount: 289,
        },
        {
          id: "b8",
          name: "Glow Secrets",
          slug: "glow-secrets",
          images: [
            "https://picsum.photos/400/500?beauty15a",
            "https://picsum.photos/400/500?beauty15b",
            "https://picsum.photos/400/500?beauty15c",
          ],
          pfp: "https://picsum.photos/100/100?beauty15pfp",
          rating: 4.9,
          reviewCount: 456,
        },
      ],
    },
    {
      title: "Gifts",
      slug: "gifts",
      shops: [
        {
          id: "g1",
          name: "Gift Box",
          slug: "gift-box",
          images: [
            "https://picsum.photos/400/500?gift1a",
            "https://picsum.photos/400/500?gift1b",
            "https://picsum.photos/400/500?gift1c",
          ],
          pfp: "https://picsum.photos/100/100?gift1pfp",
          rating: 4.9,
          reviewCount: 623,
        },
        {
          id: "g2",
          name: "Personalized Gifts",
          slug: "personalized-gifts",
          images: [
            "https://picsum.photos/400/500?gift2a",
            "https://picsum.photos/400/500?gift2b",
            "https://picsum.photos/400/500?gift2c",
          ],
          pfp: "https://picsum.photos/100/100?gift2pfp",
          rating: 4.8,
          reviewCount: 456,
        },
        {
          id: "g3",
          name: "Surprise Store",
          slug: "surprise-store",
          images: [
            "https://picsum.photos/400/500?gift3a",
            "https://picsum.photos/400/500?gift3b",
            "https://picsum.photos/400/500?gift3c",
          ],
          pfp: "https://picsum.photos/100/100?gift3pfp",
          rating: 4.7,
          reviewCount: 334,
        },
        {
          id: "g4",
          name: "Unique Gifts",
          slug: "unique-gifts",
          images: [
            "https://picsum.photos/400/500?gift7a",
            "https://picsum.photos/400/500?gift7b",
            "https://picsum.photos/400/500?gift7c",
          ],
          pfp: "https://picsum.photos/100/100?gift7pfp",
          rating: 4.9,
          reviewCount: 512,
        },
        {
          id: "g5",
          name: "Gift Baskets",
          slug: "gift-baskets",
          images: [
            "https://picsum.photos/400/500?gift8a",
            "https://picsum.photos/400/500?gift8b",
            "https://picsum.photos/400/500?gift8c",
          ],
          pfp: "https://picsum.photos/100/100?gift8pfp",
          rating: 4.7,
          reviewCount: 345,
        },
        {
          id: "g6",
          name: "Holiday Gifts",
          slug: "holiday-gifts",
          images: [
            "https://picsum.photos/400/500?gift9a",
            "https://picsum.photos/400/500?gift9b",
            "https://picsum.photos/400/500?gift9c",
          ],
          pfp: "https://picsum.photos/100/100?gift9pfp",
          rating: 4.8,
          reviewCount: 423,
        },
        {
          id: "g7",
          name: "Wedding Gifts",
          slug: "wedding-gifts",
          images: [
            "https://picsum.photos/400/500?gift12a",
            "https://picsum.photos/400/500?gift12b",
            "https://picsum.photos/400/500?gift12c",
          ],
          pfp: "https://picsum.photos/100/100?gift12pfp",
          rating: 4.7,
          reviewCount: 378,
        },
        {
          id: "g8",
          name: "Corporate Gifts",
          slug: "corporate-gifts",
          images: [
            "https://picsum.photos/400/500?gift10a",
            "https://picsum.photos/400/500?gift10b",
            "https://picsum.photos/400/500?gift10c",
          ],
          pfp: "https://picsum.photos/100/100?gift10pfp",
          rating: 4.6,
          reviewCount: 289,
        },
      ],
    },
  ];
}
